config/routes.rb
Rails.application.routes.draw do
  root 'store#index'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  ActiveAdmin.routes(self)

  post '/products/:product_id/comments' => 'comments#create', as: 'product_comments'
  get '/catalog' => 'products#index', as: 'products'

  resources :visitors, only: [:create]
  resources :articles, only: [:index, :show]
  resources :orders, only: [:index, :show, :new, :create]
  resources :users, only: [:show]
  resource :shopping_cart, only: [:show, :destroy]
  resource :shopping_cart_items, only: [:create, :destroy]
  resources :contacts, only: [:new, :create] do
    post 'callback', on: :collection, as: :callback
  end
  resources :brands, only: [:show]
  resources :attachments, only: [:index]
  get ':id' => 'pages#show', as: :page

  get 'c/:id' => 'categories#show', :as => :category_short
  get 'c/:category/:id' => 'categories#show', :as => :category_long
  get '/p/:id' => 'products#show', as: 'product'
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  
  paginates_per 10

  friendly_id :title, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_cart
  before_action :find_categories

  def index
    @articles = Article.all.page params[:page]
  end

  def show
    @article = Article.friendly.find(params[:id])
  end
end

app/views/articles/index.html.erb
<% content_for :breadcrumbs do %>
  <div id="heading-breadcrumbs" class="col-md-12">
    <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1>Blog</h1>
          </div>
          <div class="col-md-5">
            <ul class="breadcrumb">
              <li><%= link_to t('home'), root_path %></li>
               <li>News and Articles</li>
            </ul>
          </div>
        </div>
    </div>
  </div>
<% end %>

<div class="content">
  <div class="container">
    <% @articles.each do |article| %>
      <section>
        <div class="row">
          <div class="col-md-12">
            <div class="heading">
              <h2><%= link_to article.title, article_path(article) %></h2>
            </div>
            <p class="lead">
              <%= sanitize article.description %>
            </p>
            <p class="read-more">
                <%= link_to "Learn More", article_path(article), class: "btn btn-primary" %>
            </p>
          </div>
        </div>
      </section>
    <% end %>
  </div>
</div>

<%= paginate @articles %>

app/views/articles/show.html.erb
<% content_for :title do %><%= @article.meta_title %><% end %>
<% content_for :description do %><%= @article.meta_description %><% end %>
<% content_for :keywords do %><%= @article.meta_keywords %><% end %>

<% content_for :breadcrumbs do %>
  <div id="heading-breadcrumbs" class="col-md-12">
    <div class="container">
        <div class="row">
          <ul class="breadcrumb">
            <li><%= link_to t('home'), root_path %></li>
            <li><%= link_to 'News and Articles', articles_path %></li>
            <li><%= @article.title %></li>
          </ul>
        </div>
    </div>
  </div>
<% end %>

<div id="blog-post">
  <div class="box">
    <div class="heading">
      <h1><%= @article.title %></h1>
    </div>

    <div id="post-content">
      <%= sanitize @article.content %>
      <hr>
          <div class="social-likes" data-title="<%= @article.title %>" data-counters="no">
            <div class="facebook" title="#">Facebook</div>
            <div class="twitter" title="#">Twitter</div>
            <div class="plusone" title="#">Google+</div>
          </div>
    </div>
  </div>
</div>