config/routes.rb
Rails.application.routes.draw do
  root 'store#index'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  ActiveAdmin.routes(self)

  post '/products/:product_id/comments' => 'comments#create', as: 'product_comments'
  get '/catalog' => 'products#index', as: 'products'

  resources :visitors, only: [:create]
  resources :articles, only: [:index, :show]
  resources :orders, only: [:index, :show, :new, :create]
  resources :users, only: [:show]
  resource :shopping_cart, only: [:show, :destroy]
  resource :shopping_cart_items, only: [:create, :destroy]
  resources :contacts, only: [:new, :create] do
    post 'callback', on: :collection, as: :callback
  end
  resources :brands, only: [:show]
  resources :attachments, only: [:index]
  get ':id' => 'pages#show', as: :page

  get 'c/:id' => 'categories#show', :as => :category_short
  get 'c/:category/:id' => 'categories#show', :as => :category_long
  get '/p/:id' => 'products#show', as: 'product'
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart

  def remove(object, quantity = 1)
    cart_item = item_for(object)
    return unless cart_item

    cart_item.delete
  end

  def total
    subtotal
  end

  def self.remove_old_records
    old_record = ShoppingCart.where('created_at < ?', 7.days.ago)
    delete(old_record)
  end

  def empty?
    false
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_cart
  before_action :find_categories

  def show
  end

  def destroy
    @shopping_cart.clear
    redirect_to root_path
  end
end

app/views/shopping_carts/show.html.erb
<div id="basket">
  <div class="box">
      <h1>Cart</h1>
      <div class="table-responsive">
          <table class="table">
              <thead>
                  <tr>
                      <th colspan="2"><% t("product") %></th>
                      <th><% t("quantity") %></th>
                      <th><% t("price") %></th>
                      <th colspan="2"><% t("total") %></th>
                  </tr>
              </thead>
              <tbody>
                <% @shopping_cart.shopping_cart_items.each do |shopping_cart_item| %>
                  <tr>
                      <td>
                          <%= link_to product_path(shopping_cart_item.item) do %>
                              <%= image_tag shopping_cart_item.item.image_url(:preview), class:"img-responsive" %>
                          <% end %>
                      </td>
                      <td>
                        <%= link_to shopping_cart_item.item.title, product_path(shopping_cart_item.item) %>
                      </td>
                      <td>
                          <input type="number" value="<%= shopping_cart_item.quantity %>" class="form-control">
                      </td>
                      <td>
                        <%= shopping_cart_item.item.price %>
                      </td>
                      <td>
                        <%= shopping_cart_item.subtotal %></td>
                      <td>
                        <%= link_to shopping_cart_items_path(:product_id => shopping_cart_item.item.id), method: :delete do %>
                          <i class="fa fa-trash-o"></i>
                        <% end %>
                      </td>
                  </tr>
                <% end %>
              </tbody>
              <tfoot>
                  <tr>
                      <th colspan="5"><%= t("total") %>:</th>
                      <th colspan="2">EUR <%= @shopping_cart.total %></th>
                  </tr>
              </tfoot>
          </table>
      </div>

      <div class="box-footer">
          <div class="pull-left">
             <%= link_to :back, class: "btn btn-default" do %>
              <i class="fa fa-chevron-left"></i> <% t("continue_shopping") %>
             <% end %>
          </div>
          <div class="pull-right">
            <%= link_to t('clear_cart'), @shopping_cart, method: :delete, class: "btn btn-default"%>
             <%= link_to new_order_path, class: "btn btn-primary" do %>
             <%= t("confirm_order") %> <i class="fa fa-chevron-right"></i>
             <% end %>
          </div>
      </div>
  </div>
</div>