config/routes.rb
Rails.application.routes.draw do
  root 'store#index'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  ActiveAdmin.routes(self)

  post '/products/:product_id/comments' => 'comments#create', as: 'product_comments'
  get '/catalog' => 'products#index', as: 'products'

  resources :visitors, only: [:create]
  resources :articles, only: [:index, :show]
  resources :orders, only: [:index, :show, :new, :create]
  resources :users, only: [:show]
  resource :shopping_cart, only: [:show, :destroy]
  resource :shopping_cart_items, only: [:create, :destroy]
  resources :contacts, only: [:new, :create] do
    post 'callback', on: :collection, as: :callback
  end
  resources :brands, only: [:show]
  resources :attachments, only: [:index]
  get ':id' => 'pages#show', as: :page

  get 'c/:id' => 'categories#show', :as => :category_short
  get 'c/:category/:id' => 'categories#show', :as => :category_long
  get '/p/:id' => 'products#show', as: 'product'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :read, Order, user: user
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  
  paginates_per 10

  friendly_id :title, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :product
  validates :file, presence: true

  mount_uploader :file, DocumentUploader

  scope :uniq_by_product, -> { select('DISTINCT ON (product_id) *') }
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  extend FriendlyId
  has_many :products, dependent: :destroy

  friendly_id :name, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  has_and_belongs_to_many :products

  has_ancestry :orphan_strategy => :rootify, :cache_depth => true

  friendly_id :name, use: :slugged

  translates :name, :description

  active_admin_translates :name, :description

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end

  def products_with_children
    return products unless has_children?
    children.inject(products) { |a, e| a << e.products }
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  has_many :comment_replies
  
  validates :user_name, :body, presence: true

  default_scope { order(:updated_at) }
end

app/models/comment_reply.rb
class CommentReply < ActiveRecord::Base
	belongs_to :comment
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string
  attr_accessor :phone, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, GalleryUploader
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :shopping_cart_items, dependent: :destroy
  belongs_to :user
  validates :adress, :phone, :post_code, presence: true

  def add_line_items_from_cart(cart)
    cart.shopping_cart_items.each do |item|
      item.owner_id = nil
      item.owner_type = nil
      shopping_cart_items << item
    end
  end

  def add_total_price(cart)
    self.total_price = cart.total
  end

  def name
    "#{firstname} #{lastname}"
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged

  translates :title, :content

  active_admin_translates :title, :content
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  translates :title, :description, :characteristics

  active_admin_translates :title, :description, :characteristics

  mount_uploader :image, ImageUploader

  friendly_id :title, use: :slugged

  paginates_per 15

  belongs_to :brand

  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories
  has_many :attachments, dependent: :destroy
  has_many :galleries, dependent: :destroy

  accepts_nested_attributes_for :attachments, allow_destroy: true
  accepts_nested_attributes_for :galleries, allow_destroy: true

  validates :categories, :tags, :title, :description, :image, :price, presence: true

  scope :all_except, ->(product) { where.not(id: product.id) }
  scope :similar, ->(product) {
    joins(:tags).where('tags.name = ?', product.tags.first.name.to_s) if product.tags.present?
  }
  scope :novinki, -> { includes(:tags).where(tags: {name: 'novinki'}).references(:tags) }
  scope :popular, -> { includes(:tags).where(tags: {name: 'popular'}).references(:tags) }

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end

  def delivery_cost
    if brand.name == 'Ладас'
      '0'
    elsif brand.name == 'Babygrai' && price > 1000
      '0'
    else
      '150'
    end
  end
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart

  def remove(object, quantity = 1)
    cart_item = item_for(object)
    return unless cart_item

    cart_item.delete
  end

  def total
    subtotal
  end

  def self.remove_old_records
    old_record = ShoppingCart.where('created_at < ?', 7.days.ago)
    delete(old_record)
  end

  def empty?
    false
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :product_tags
  has_many :products, through: :product_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/models/visitor.rb
class Visitor
  include ActiveModel::Model
  attr_accessor :email, :string
  validates_presence_of :email
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    list_id = Rails.application.secrets.mailchimp_list_id
    result = mailchimp.lists(list_id).members.create(
      body: {
        email_address: self.email,
        status: 'subscribed'
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/store_helper.rb
module StoreHelper
  def product_feature(features)
    return if features.nil? || features.empty?

    html = <<-HTML
    <div class="ribbon #{features}">
        <div class="theribbon">#{message(features)}</div>
        <div class="ribbon-background"></div>
    </div>
    HTML

    html.html_safe
  end

  private

  def message(features)
    case features
    when 'sale'
      'sale'
    when 'new'
      'new'
    when 'gift'
      'Free shipping'
    end
  end
end

app/views/layouts/_breadcrumbs.html.erb
<% content_for :breadcrumbs do %>
  <div id="heading-breadcrumbs" class="col-md-12">
    <div class="container">
        <div class="row">
          <ul class="breadcrumb">
            <li><%= link_to t('home'), root_path %></li>
             <li><%= @product.title %></li>
          </ul>
        </div>
    </div>
  </div>
<% end %>

app/views/layouts/_cart.html.erb
<%= link_to shopping_cart_path, class: "btn btn-primary" do %>
  <i class="fa fa-shopping-cart"></i>
  <% if @shopping_cart && @shopping_cart.has_items? %>
    <span class="hidden-sm">EUR <%= (@shopping_cart.total) %></span>
  <% else %>
    <span class="hidden-sm"><%= t('your_cart_is_empty') %></span>
  <% end %>
<% end %>

app/views/layouts/_copyright.html.erb
<div id="copyright">
    <div class="container">
        <div class="col-md-6">
            <p class="pull-left">© 2018 Gymrek.com</p>
            <%= link_to 'en', url_for( :locale => 'en' ) %>
            <%= link_to 'nl', url_for( :locale => 'nl' ) %>
        </div>
        <div class="col-md-6">
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <h4><%= t("information") %></h4>
                <ul>
                    <li>
                        <%= link_to t("about_us"), page_path("o-nas") %>
                    </li>
                    <li>
                        <%= link_to t("payment_and_delivery"), page_path("oplata-i-dostavka") %>
                    </li>
                    <li>
                        <%= link_to t("blog"), articles_path %>
                    </li>
                </ul>
            </div>
            <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <h4><%= t("support") %></h4>
                <ul>
                    <li>
                        <%= link_to t("contact_us"), new_contact_path %>
                    </li>
                    <li>
                        <%= link_to t("goods_return"), page_path("oplata-i-dostavka") %>
                    </li>
                </ul>
            </div>
            <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <h4><%= t("phone_number") %></h4>
                <ul>
                    <li><a href="#"> +32 492 34 37 51</a></li>
                </ul>
            </div>
            <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <h4><%= t("we_are_in_social_networks") %></h4>
                <div class="social">
                    <a href="#" class="facebook external" data-animate-hover="shake"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="twitter external" data-animate-hover="shake" ><i class="fa fa-twitter"></i></a>
                    <a href="#" class="instagram external" data-animate-hover="shake"><i class="fa fa-instagram"></i></a>
                </div>

            </div>
            <!-- /.col-md-3 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default yamm" role="navigation" id="navbar">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand home" href="/">
                <img src="/logo.jpg">
            </a>
            <div class="navbar-buttons">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-align-justify"></i>
                </button>
            </div>
        </div>
        <!--/.navbar-header -->
        <div class="navbar-collapse collapse" id="navigation">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="/"><%= t('home') %></a>
                </li>
                <li>
                    <%= link_to t("catalog"), products_path %>
                </li>
                <li>
                    <%= link_to t("payment_and_delivery"), page_path("oplata-i-dostavka") %>
                </li>
                <!-- <li>
                    <%= link_to "О брендах", attachments_path %>
                </li> -->
                <li>
                    <%= link_to t("contact"), new_contact_path %>
                </li>
                <li>
                    <%= link_to t("about_us"), page_path("o-nas") %>
                </li>
            </ul>
            <%= search_form_for Product.ransack(params[:q]), html: {class: "navbar-form navbar-right", role: t("search") } do |f| %>
                <div class="input-group">
                  <%= f.search_field :title_cont, placeholder: t("search"), class: "form-control" %>
                  <span class="input-group-btn">
                    <button type="submit" class="btn btn-no-margin"><i class="fa fa-search"></i></button>
                  </span>
                </div>
            <% end %>
        </div>
        <!--/.nav-collapse -->


        <!--/.nav-collapse -->
    </div>
    <!-- /.container -->
</div>

app/views/layouts/_sidebar.html.erb
<div class="panel panel-default sidebar-menu fclass">
    <div class="panel-heading">
        <h3 class="panel-title"><%= t('categories') %></h3>
    </div>
    <div class="panel-body">
      <%= arranged_tree_as_list(@categories, {:sort_by => [:position],
          :ul_class_top => ["nav", "nav-pills", "nav-stacked", "category-menu", "menu_active"]}) do |category| %>
        <%= link_to category.name, category_path(category), class: category.custom_style %>
      <% end %>
    </div>
</div>

app/views/layouts/_top.html.erb
<div id="top">
    <div class="container">
        <div class="row">
            <div class="col-sm-5 contact">
                <a href="#" data-toggle="modal" data-target="#callback-modal" class="btn btn-primary btn-sm"><i class="fa fa-phone">
                </i><%= t('request_a_call_back') %>
                </a>
            </div>
            <div class="col-sm-7">
                <div class="login">
                  <% if user_signed_in? %>
                      <%= link_to t("login_out"), destroy_user_session_path, method: :delete %>
                  <% else %>
                      <a href="#" data-toggle="modal" data-target="#login-modal">
                        <i class="fa fa-sign-in"></i> Login
                      </a>
                      <%= link_to new_user_session_path do %>
                        <i class="fa fa-user"></i> <%= t('registration') %>
                      <% end %>
                  <% end %>
                  <%= render 'layouts/cart' %>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login"><%= t('login') %></h4>
                </div>
                <div class="modal-body">
                    <%= form_for(:user, :url => user_session_path, :html => { :role => 'form'}) do |f| %>
                        <div class="form-group">
                            <%= f.email_field :email, :autofocus => true, placeholder: t('email'), class: 'form-control' %>
                        </div>
                        <div class="form-group">
                            <%= f.password_field :password, placeholder: t('password'), class: 'form-control' %>
                        </div>
                        <%= f.submit t('login'), :class => 'btn btn-primary' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="callback-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login"><%= t("call_back") %></h4>
                </div>
                <div class="modal-body">
                    <%= form_for(:contact, url: callback_contacts_path, :html => { :role => 'form'}) do |f| %>
                        <div class="form-group">
                            <%= f.text_field :name, :autofocus => true, placeholder: t('name'), class: 'form-control', required: true%>
                        </div>
                        <div class="form-group">
                            <%= f.text_field :phone, placeholder: t('phone_number'), class: 'form-control', pattern: "[+0-9]+" %>
                        </div>
                        <%= f.submit t('request_a_call_back'), :class => 'btn btn-primary' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <div id="top">
    <div class="container">
        <div class="col-md-6 offer">
            <a href="#"><i class="fa fa-phone"></i> +3 8(096) 543 38 24</a>&nbsp
            <a href="#" data-toggle="modal" data-target="#callback-modal" class="btn btn-success btn-sm"><i class="fa fa-phone">
                </i>Заказать обратный звонок
            </a>
        </div>
        <div class="col-md-6">
            <ul class="menu">
                <li><% if user_signed_in? %>
                        <%= link_to "Выход", destroy_user_session_path, method: :delete %>
                    <% else %>
                        <a href="#" data-toggle="modal" data-target="#login-modal">Войти</a>
                    <% end %>
                </li>
                <li>
                    <% if user_signed_in? %>
                        <%= link_to root_path do %>
                            <i class="fa fa-user"></i>
                            <%= link_to current_user.email, orders_path %>
                        <% end %>
                    <% else %>
                        <%= link_to 'Регистрация', new_user_session_path %>
                    <% end %>
                </li>
                <li>
                    <%= link_to "Контакты", new_contact_path %>
                </li>
                <%= render 'layouts/cart' %>
            </ul>




        </div>
    </div>
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Войти</h4>
                </div>
                <div class="modal-body">
                    <%= form_for(:user, :url => user_session_path, :html => { :role => 'form'}) do |f| %>
                        <div class="form-group">
                            <%= f.label :email, "Ел. почта" %>
                            <%= f.email_field :email, :autofocus => true, class: 'form-control' %>
                        </div>
                        <div class="form-group">
                            <%= f.label :password, "Пароль" %>
                            <%= f.password_field :password, class: 'form-control' %>
                        </div>
                        <%= f.submit 'Войти', :class => 'btn btn-primary' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="callback-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Обратный звонок</h4>
                </div>
                <div class="modal-body">
                    <%= form_for(:contact, url: callback_contacts_path, :html => { :role => 'form'}) do |f| %>
                        <div class="form-group">
                            <%= f.label :name, "Ваше имя" %>
                            <%= f.text_field :name, :autofocus => true, class: 'form-control', required: true%>
                        </div>
                        <div class="form-group">
                            <%= f.label :phone, "Телефон" %>
                            <%= f.text_field :phone, class: 'form-control', pattern: "[0-9]+" %>
                        </div>
                        <%= f.submit 'Заказать звонок', :class => 'btn btn-primary' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gymrek.com" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gymrek.com" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700italic,700,500italic,500,400italic,300,300italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

    <script>
      !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(n,o);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
      analytics.load("KwySmKQtKCS5SCcElgevJ24CnM3CbMYF");
      analytics.page();
      }}();
    </script>
    <style>
.btn-primary {
    color: white;
    background-color: #337ab7;
    border-color: #337ab7;
  }
  #top .login a.btn.btn-primary {
    color: white;
}
.btn-primary:hover {
    border-color: white !important;
}
.btn-primary:hover {
    color: #fff;
    background-color: #337ab7 !important;
}
#top .login a.btn.btn-primary:hover {
    color: #fff;
    border-color: white !important;
}
a {
    color: #337ab7;
    text-decoration: none;
}
a:hover, a:focus {
    color: #337ab7;
}
.panel.sidebar-menu .panel-heading h1, .panel.sidebar-menu .panel-heading h2, .panel.sidebar-menu .panel-heading h3, .panel.sidebar-menu .panel-heading h4, .panel.sidebar-menu .panel-heading h5 {
    display: inline-block;
    border-bottom: solid 5px #337ab7;
  }
.nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus {
    color: #ffffff;
    background-color: gray;
}
#footer ul a:hover {
    color: #337ab7;
    text-decoration: none;
}


.nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus {
    color: #ffffff;
    background-color: #337ab7;
}

.navbar ul.nav>li.active>a, .navbar ul.nav>li.open>a {
    text-decoration: none !important;
    border-top: solid 5px #294d76;
}

.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:hover, .navbar-default .navbar-nav>.active>a:focus {
    color: white;
    background-color: #467fbf;
}

button.btn.btn-no-margin {
    color: white;
    background-color: #337ab7;
    border: solid;
    border-width: 0.5px;
    height: 34px;
    border-color: #ccc;
}

button.btn.btn-no-margin:hover {
    color: white;
    background-color: #337ab7;
}

.nav-tabs {
    border-bottom: 1px solid #337ab7;
}

.navbar ul.nav>li>a:hover {
    border-top: solid 5px #467fbf;
}

.navbar-default .navbar-nav>li>a:hover, .navbar-default .navbar-nav>li>a:focus {
    color: #555555;
    background-color: #92b3d9;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:hover, .nav-tabs>li.active>a:focus {
    color: #555555;
    background-color: #ffffff;
    border: 1px solid #337ab7;
    border-bottom-color: transparent;
    cursor: default;
}
.pagination>.active>a, .pagination>.active>span, .pagination>.active>a:hover, .pagination>.active>span:hover, .pagination>.active>a:focus, .pagination>.active>span:focus {
    z-index: 2;
    color: #ffffff;
    background-color: #337ab7;
    border-color: #337ab7;
}
.pagination>li>a, .pagination>li>span {
    padding: 6px 12px;
    line-height: 1.42857143;
    text-decoration: none;
    color: #337ab7;
    background-color: #ffffff;
    border: 1px solid #dddddd;
}
.heading h1, .heading h2, .heading h3, .heading h4, .heading h5 {
    border-bottom: solid 5px #337ab7;
}
.alert-success {
    background-color: #337ab7;
    border-color: #337ab7;
    color: white;
    margin-top: 2px;
}
.btn-primary:focus, .btn-primary.focus {
    color: white;
    background-color: #337ab7;
    border-color: #337ab7;
}

.product .text h3 {
    font-size: 14px;
    font-weight: 700;
    height: 40.6px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
}

</style>
  </head>

  <body>
      <%= render 'layouts/top' %>
      <%= render 'layouts/navbar' %>
      <div id="all">
        <div id="content">
            <%= yield(:breadcrumbs) %>
            <div class="container">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
        </div>
        <%= render 'layouts/footer' %>
        <%= render 'layouts/copyright' %>
      </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>